#!/usr/bin/env python3
'''Solves a linear system of equations.'''
import solvers
import linsolveio as io

INPUT_FILE = 'linsolve.in'
OUTPUT_FILE = 'linsolve.out'


def main():
    '''Main driver routine.'''
    aa, bb = io.read_input(INPUT_FILE)
    xx = solvers.gaussian_eliminate(aa, bb)
    io.write_result(OUTPUT_FILE, xx)


if __name__ == '__main__':
    main()
